name: bliindaidating
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '^3.8.0' # Keep your SDK constraint as is

dependencies:
  flutter:
    sdk: flutter

  go_router: ^14.0.0
  cupertino_icons: ^1.0.8
  
  # --- Firebase Dependencies (ALL UPDATED TO ABSOLUTE LATEST STABLE FOR COMPATIBILITY) ---
  # These versions are the most recent stable releases as of June 30, 2025.
  # Upgrading all simultaneously is the most reliable way to resolve deep dependency conflicts.
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.7
  firebase_analytics: ^11.5.0
  firebase_crashlytics: ^4.3.7
  google_sign_in: ^7.0.0
  firebase_app_check: ^0.3.2+7
  firebase_remote_config: ^5.4.5
  firebase_messaging: ^15.2.7
  cloud_functions: ^5.5.2 # This is the absolute latest for cloud_functions

  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
        - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
          style: italic
