# pubspec.yaml
name: bliindaidating
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  go_router: ^14.0.0
  cupertino_icons: ^1.0.8

  # --- Supabase Dependency ---
  supabase_flutter: ^2.9.1
  flutter_dotenv: ^5.2.1
  image_picker: ^1.1.2

  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.11
  provider: ^6.1.2 # Added for state management (e.g., theme)
  intl: ^0.19.0 # NEW: Added for date formatting
  http: ^1.2.1 # FIXED: ADDED HTTP PACKAGE
  uuid: ^4.4.0 # FIXED: ADDED UUID PACKAGE
  cross_file: ^0.3.3+1 # NEW: Add this line for XFile in profile_service.dart

  # --- JSON Serialization Dependencies ---  <-- ADD THESE LINES
json_annotation: ^4.9.0 # Updated to meet json_serializable's requirement

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # --- Code Generation Dependencies ---  <-- ADD THESE LINES
  build_runner: ^2.4.8 # Ensure this is the latest stable version
  json_serializable: ^6.7.1 # Ensure this is the latest stable version

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/svg/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
        - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
          style: italic