name: bliindaidating
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0' # Flexible SDK constraint for Flutter 3.10.6

dependencies:
  flutter:
    sdk: flutter

  go_router: ^14.0.0
  cupertino_icons: ^1.0.8
  
  # --- Firebase Dependencies (Current, building versions) ---
  # These versions are the ones from your pubspec that allowed the build to pass the 'Undefined name main' error.
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.2
  cloud_firestore: ^4.13.4
  firebase_storage: ^11.5.4
  firebase_analytics: ^10.8.0
  firebase_crashlytics: ^3.4.9
  google_sign_in: ^6.1.0
  firebase_app_check: ^0.2.1+9
  firebase_remote_config: ^4.3.14
  firebase_messaging: ^14.7.10
  cloud_functions: ^4.6.0 # Correct package for Cloud Functions

  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.11
  google_fonts: ^6.1.0 # ADDED: For GoogleFonts usage in feature_card_widget.dart

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
        - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
          style: italic
