// lib/firebase_options.dart

// File generated by FlutterFire CLI.
// Do not modify this file.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

// This file is manually generated due to flutterfire configure issues.
// REPLACE THE VALUES BELOW WITH YOUR ACTUAL FIREBASE CONFIG FROM THE CONSOLE.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again',
        );
      case TargetPlatform.web:
        return web;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // NOTE: For Android and iOS, you would get these specific keys from your
  // Firebase project settings for each respective platform's app.
  // For now, these are placeholders or can be filled with your web keys
  // if you only plan to target web initially and need to compile.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY', // <<< REPLACE THIS WITH ACTUAL ANDROID KEY
    appId: 'YOUR_ANDROID_APP_ID', // <<< REPLACE THIS WITH ACTUAL ANDROID APP ID
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID', // <<< REPLACE THIS
    projectId: 'refined-gravity-463217-g8', // Same as web
    authDomain: 'refined-gravity-463217-g8.firebaseapp.com', // Same as web
    databaseURL: 'https://refined-gravity-463217-g8-default-rtdb.firebaseio.com', // Same as web
    storageBucket: 'refined-gravity-463217-g8.firebasestorage.app', // Same as web
    measurementId: 'G-1TDSB3MMZP', // Same as web
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY', // <<< REPLACE THIS WITH ACTUAL IOS KEY
    appId: 'YOUR_IOS_APP_ID', // <<< REPLACE THIS WITH ACTUAL IOS APP ID
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID', // <<< REPLACE THIS
    projectId: 'refined-gravity-463217-g8', // Same as web
    authDomain: 'refined-gravity-463217-g8.firebaseapp.com', // Same as web
    databaseURL: 'https://refined-gravity-463217-g8-default-rtdb.firebaseio.com', // Same as web
    storageBucket: 'refined-gravity-463217-g8.firebasestorage.app', // Same as web
    measurementId: 'G-1TDSB3MMZP', // Same as web
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3izscdSEpnHvH1A7Qrq9F21ISErERPtA',
    appId: '1:580431966370:web:a6b0e3633de14115be67fb',
    messagingSenderId: '580431966370',
    projectId: 'refined-gravity-463217-g8',
    authDomain: 'refined-gravity-463217-g8.firebaseapp.com',
    databaseURL: 'https://refined-gravity-463217-g8-default-rtdb.firebaseio.com',
    storageBucket: 'refined-gravity-463217-g8.firebasestorage.app',
    measurementId: 'G-1TDSB3MMZP',
  );
}
